
services:
  database:
    image: mysql:5.7
    container_name: Cognizant 
    restart: always
    environment:
      MYSQL_DATABASE: 'easy_fitness'   
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'Spring@2024'      
      MYSQL_ROOT_PASSWORD: 'Pr#jeto2024'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
